version: "3.9"

services:
  db:
    image: postgres:16
    container_name: gin_register_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fixit
      POSTGRES_USER: fixit
      POSTGRES_PASSWORD: secret
    ports:
      - "5438:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixit -d fixit"]
      interval: 5s
      timeout: 3s
      retries: 10


  app:
    build:
      context: .
      dockerfile: docker/dev/app/Dockerfile
    container_name: gin_register_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://fixit:secret@db:5432/fixit?sslmode=disable
      ADDR: ${ADDR:-:8080}
    volumes:
      - ./:/app
    expose:
      - "8080"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        PKG_MGR: npm
    container_name: gin_register_web
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"

volumes:
  pgdata:
