root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd"
bin = "tmp/main"

include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
send_interrupt = true
stop_on_error = true

[log]
time = true

[screen]
clear_on_rebuild = true